language: objective-c
osx_image: xcode9.3

cache:
  yarn: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew

install:
  - rvm use system
  - brew install yarn
  - sudo gem install cocoapods
  - sudo gem install xcpretty

before_script:
  - set -o pipefail
  - cd example
  - yarn install
  - cd ios
  - pod install

script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild test
    -scheme example
    -configuration Debug
    -workspace example.xcworkspace
    -destination "platform=iOS Simulator,name=iPhone X"
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
